---
# add the config of STATISTICS to seafevents.conf

- name: add the config to seafevents.conf
  blockinfile: 
      path: "{{ deploy_path }}/conf/seafevents.conf"
      marker: "# {mark} ANSIBLE MANAGED BLOCK CACHE"
      insertafter: EOF
      block: |
          [STATISTICS]
          enabled = true
      backup: no
