---
# add the config about S3 not AWS to seafile.conf

- name: add the config of AWS S3
  blockinfile:
    path: "{{ deploy_path }}/conf/seafile.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK S3"
    insertafter: EOF
    block: |
        [commit_object_backend]
        name = s3
        bucket = {{ bucket_commit_name }}
        key_id = {{ your_key_id }}
        key = {{ your_secret_key }}
        
        [fs_object_backend]
        name = s3
        bucket = {{ bucket_fs_name }}
        key_id = {{ your_key_id }}
        key = {{ your_secret_key }}
        
        [block_backend]
        name = s3
        bucket = {{ bucket_block_name }}
        key_id = {{ your_key_id }}
        key = {{ your_secret_key }}
