---
# add the config to seahub_settings.py

- name: add extra config to seahub_settings.py
  blockinfile:
      path: "{{ deploy_path }}/conf/seahub_settings.py"
      marker: "# {mark} ANSIBLE MANAGED BLOCK CACHE"
      insertafter: EOF
      block: |
          CACHES = {
              'default': {
                  'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
                  'LOCATION': '{{ cache_vip }}:11211',
              }
          }

          TIME_ZONE                           = 'Asia/Shanghai'
          SITE_BASE                           = 'http://{{ web_vip }}'
          SITE_NAME                           = 'Seafile Server'
          SITE_TITLE                          = 'Seafile Server'
          SITE_ROOT                           = '/'
          ENABLE_SIGNUP                       = False
          ACTIVATE_AFTER_REGISTRATION         = False
          SEND_EMAIL_ON_ADDING_SYSTEM_MEMBER  = True
          SEND_EMAIL_ON_RESETTING_USER_PASSWD = True
          CLOUD_MODE                          = False
          FILE_PREVIEW_MAX_SIZE               = 30 * 1024 * 1024
          SESSION_COOKIE_AGE                  = 60 * 60 * 24 * 7 * 2
          SESSION_SAVE_EVERY_REQUEST          = False
          SESSION_EXPIRE_AT_BROWSER_CLOSE     = False
          FILE_SERVER_ROOT                    = 'http://{{ web_vip }}/seafhttp'

          AVATAR_FILE_STORAGE = 'seahub.base.database_storage.DatabaseStorage'
          COMPRESS_CACHE_BACKEND = 'django.core.cache.backends.locmem.LocMemCache'
          OFFICE_CONVERTOR_NODE = True
      backup: yes
